spring.application.name=module-a-backend
server.port=8081

# For MongoDB Atlas (uncomment and replace)
spring.data.mongodb.uri=mongodb+srv://inothma981:Swiftie%4002@cluster0.sldpw0f.mongodb.net/smartcampusdb?appName=Cluster0

# Logging (helpful during development)
logging.level.org.springframework.data.mongodb=DEBUG

# JWT Configuration
jwt.secret=mySecretKey123456789012345678901234567890
jwt.expiration=86400000

# File Upload Configuration
file.upload-dir=uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=20MB